---
### Set Open Stack Flavor (machine size)

- name: Set Small Flavor ID Fact
  set_fact:
    os1_flavor_id: "{{ os1_small_flavor_id }}"
  when: instance_flavor == 'small'

- name: Set Medium Flavor ID Fact
  set_fact:
    os1_flavor_id: "{{ os1_medium_flavor_id }}"
  when: instance_flavor == 'medium'

- name: Set Large Flavor ID Fact
  set_fact:
    os1_flavor_id: "{{ os1_large_flavor_id }}"
  when: instance_flavor == 'large'

- name: Set Large Flavor ID Fact
  set_fact:
    os1_flavor_id: "{{ os1_xl_flavor_id }}"
  when: instance_flavor == 'xl'

### Set Image ID (linux distro)

- name: Set RHEL Image ID Fact
  set_fact:
    os1_image_id: "{{ os1_rhel_image_id }}"
  when: os1_distro_variant == 'rhel'

#- name: Set Centos Image ID Fact
#  set_fact:
#    os1_image_id: "{{ os1_centos_image_id }}"
#  when: os1_distro_variant == 'centos'

- name: Set Fedora Image ID Fact
  set_fact:
    os1_image_id: "{{ os1_fedora_image_id }}"
  when: os1_distro_variant == 'fedora'

