---
#####################################################################################################################
#  Use OS1 Public or Private to create a new host
#####################################################################################################################

- hosts: 127.0.0.1
  remote_user: root
  connection: local
  roles:
    - new-os1-instance
  tags:
    - new-os1-instance

  vars_prompt:
    - name: "openstack_env"
      prompt: "os1 public or private?"
      private: no
      default: private

    - name: "os1_password"
      prompt: "OS1 password?"
      private: yes
      default: fakePassword

#####################################################################################################################
#  Necessary at the playbook level (not a dependency) because host might not be bootstrapped and can't gather facts.
#  Gather Fact false can only be set at the playbook level
#####################################################################################################################


- hosts: openstack_instances
  remote_user: cloud-user
  sudo: true
  gather_facts: false
  roles:
    - { role: fedora, when: os1_distro_variant == 'fedora' }
  tags:
    - fedora


- hosts: openstack_instances
  remote_user: cloud-user
  sudo: true
  gather_facts: false
  roles:
    - { role: rhel, when: os1_distro_variant == 'rhel' or os1_distro_variant == 'centos'  }
  tags:
    - rhel

  vars_prompt:
    - name: "rhn_password"
      prompt: "RHN password?"
      private: yes
      default: fakePassword


- hosts: openstack_instances
  remote_user: cloud-user
  sudo: true
  gather_facts: false
  roles:
    - { role: bpms-design, when: instance_name == 'bpms-design' }
  tags:
    - bpms-design


- hosts: openstack_instances
  remote_user: cloud-user
  gather_facts: false
  sudo: true
  roles:
    - { role: file-server, when: instance_name == 'file-server' }
  tags:
    - file-server
