- hosts: openstack_instances
  remote_user: cloud-user
  sudo: true
  gather_facts: false
  tasks:

  - name: Install HA Proxy Package
    yum:
      name: haproxy
      state: latest

  - name: Copy HA Proxy Config
    copy:
      src: files/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: "644"

  - name: Start and Enable HA Proxy Service
    service:
      name: haproxy
      state: started
      enabled: yes